### ISSUE TITLE
Created KMS keys aren't outputted in arn form

### ISSUE THREAD

**Issue by jakepruitt** [mapbox/cloudformation-kms#2]
At the moment, the output of a newly created kms key is just the key id, not the entire ARN. This breaks the assumption made by downstream users that expect a full arn.

cc/ @rclark @xrwang

**Comment by xrwang** [comment]
Adding to this: Taking the outputted KMS keys and then adding the arn to it seems to delete the key itself, rather than regenerate. Not sure if this is expected.

**Comment by rclark** [comment]
Quickfix: change [the `ref('Key')` here](https://github.com/mapbox/cloudformation-kms/blob/master/cloudformation/cloudformation-kms.template.js#L48) to `getAtt('Key', 'Arn')`.

https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-kms-key.html#d0e85286

**Comment by arunasank** [comment]
@xrwang's fixes in https://github.com/mapbox/cloudformation-kms/commits/secret have fixed this. 

Created a staging stack in `ap-northeast-2`, and tested to see how it worked with/without the `LegacyArn` parameter. In both cases, the output was `arn:aws:kms:us-east-1:<account-id>:key/<key-sha>`
